# PICclock Configure Script (PowerShell)

$ConfigFile = "config.mk"
$Errors = 0

function Find-IPE {
    if ($env:MPLAB_IPE -and (Test-Path $env:MPLAB_IPE)) {
        return $env:MPLAB_IPE
    }

    $searchPaths = @(
        "C:\Program Files\Microchip\MPLABX\v*\mplab_platform\mplab_ipe\ipecmd.exe",
        "C:\Program Files (x86)\Microchip\MPLABX\v*\mplab_platform\mplab_ipe\ipecmd.exe"
    )

    foreach ($pattern in $searchPaths) {
        $found = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($found) { return $found.FullName }
    }
    return $null
}

function Find-XC8 {
    $xc8cc = Get-Command xc8-cc -ErrorAction SilentlyContinue
    if ($xc8cc) { return $xc8cc.Source }

    $searchPaths = @(
        "C:\Program Files\Microchip\xc8\v*\bin\xc8-cc.exe",
        "C:\Program Files (x86)\Microchip\xc8\v*\bin\xc8-cc.exe"
    )

    foreach ($pattern in $searchPaths) {
        $found = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Sort-Object -Descending | Select-Object -First 1
        if ($found) { return $found.FullName }
    }
    return $null
}

function Find-DFP {
    $searchPaths = @(
        "C:\Program Files\Microchip\MPLABX\v*\packs\Microchip\PIC16F1xxxx_DFP\*",
        "C:\Program Files (x86)\Microchip\MPLABX\v*\packs\Microchip\PIC16F1xxxx_DFP\*",
        "$env:USERPROFILE\.mchp_packs\Microchip\PIC16F1xxxx_DFP\*"
    )

    foreach ($pattern in $searchPaths) {
        $found = Get-ChildItem -Path $pattern -Directory -ErrorAction SilentlyContinue | 
                 Where-Object { Test-Path "$($_.FullName)\xc8" } |
                 Sort-Object Name -Descending | Select-Object -First 1
        if ($found) { return $found.FullName }
    }
    return $null
}

Write-Host "PICclock Configure"
Write-Host ""

Write-Host -NoNewline "Checking for make... "
$make = Get-Command make -ErrorAction SilentlyContinue
if ($make) { Write-Host "found" } else { Write-Host "NOT FOUND"; $Errors++ }

Write-Host -NoNewline "Checking for java... "
$java = Get-Command java -ErrorAction SilentlyContinue
if ($java) { Write-Host "found" } else { Write-Host "NOT FOUND"; $Errors++ }

Write-Host -NoNewline "Checking for MPLAB IPE... "
$ipePath = Find-IPE
if ($ipePath) { Write-Host "found: $ipePath" } else { Write-Host "NOT FOUND"; $Errors++ }

Write-Host -NoNewline "Checking for xc8 compiler... "
$xc8Path = Find-XC8
if ($xc8Path) { Write-Host "found: $xc8Path" } else { Write-Host "NOT FOUND"; $Errors++ }

Write-Host -NoNewline "Checking for PIC16F1xxxx DFP... "
$dfpPath = Find-DFP
if ($dfpPath) { Write-Host "found: $dfpPath" } else { Write-Host "NOT FOUND (install via MPLAB X IDE: Tools > Packs > PIC16F1xxxx_DFP)"; $Errors++ }

Write-Host ""

if ($Errors -gt 0) {
    Write-Host "Configuration FAILED: $Errors required tool(s) not found"
    exit 1
}

Write-Host "Writing $ConfigFile..."

$ipePathMake = $ipePath -replace '\\', '/'
$xc8PathMake = $xc8Path -replace '\\', '/'
$dfpPathMake = ($dfpPath -replace '\\', '/') + '/xc8'

Set-Content -Path $ConfigFile -Value "# Auto-generated by configure script"
Add-Content -Path $ConfigFile -Value ""
Add-Content -Path $ConfigFile -Value "IPE := $ipePathMake"
Add-Content -Path $ConfigFile -Value "XC8 := $xc8PathMake"
Add-Content -Path $ConfigFile -Value "DFP := $dfpPathMake"

Write-Host "Done."
